# Autograd

Here we will discuss Autograd and how it works using pytorch. A lot of algorithms that we work on make use on automataic finding derivaitves. Autograd find the derivatives for you. Lets see how it works.

In [1]:
import torch
import numpy as np
from torch import tensor
from numpy import array

In [2]:
# If both the input and the output are scalars, then the gradient is a scalar.
x = tensor(1.0, requires_grad=True)
y = x ** 2
y.backward()
x.grad

tensor(2.)

In [3]:
# y.backward takes an argument called the gradient, which is used to compute vector Jacbian product and return the back a vector.
new_x = tensor(1.0, requires_grad=True)
y = new_x ** 2
y.backward(tensor(100.))
new_x.grad

tensor(200.)

In [4]:
# If input is a vector and the output is a scalar.
vector_x = tensor([1.0, 2.0], requires_grad=True)
y = vector_x.sum()
y.backward()
vector_x.grad

tensor([1., 1.])

In [5]:
# If input is a vector and output is scalar but we pass a gradient value
vector_x_back = tensor([1.0, 2.0], requires_grad=True)
y = vector_x_back.sum()
y.backward(tensor(100))
vector_x_back.grad

tensor([100., 100.])

In [6]:
vector_output_x = torch.tensor([1.0, 2.0], requires_grad=True)
y = 3 * (vector_output_x ** 2)
y.backward(tensor([1.0, 1.0]))
vector_output_x.grad

tensor([ 6., 12.])

In [7]:
x = tensor([1., 2.], requires_grad=True)
print('x:', x)
y = torch.empty(3)
y[0] = 3*x[0]**2
y[1] = x[0]**2 + 2*x[1]**3
y[2] = 10*x[1]
print('y:', y)
gradient_value = [1., 10., 100.,]
y.backward(tensor(gradient_value)) 
print('x.grad:', x.grad)

x: tensor([1., 2.], requires_grad=True)
y: tensor([ 3., 17., 20.], grad_fn=<CopySlices>)
x.grad: tensor([  26., 1240.])


In [26]:
# Now lets see a function which is of two variables

new_x = torch.tensor([1., 2.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

new_y = (new_x * 2) + (b ** 2)
new_y.backward(torch.tensor([1., 1.]))
new_x.grad
b.grad

tensor([4.])